-- Limpeza prévia (Opcional - CUIDADO em produção)
DROP TABLE IF EXISTS "LogsAuditoria" CASCADE;
DROP TABLE IF EXISTS "Interacoes" CASCADE;
DROP TABLE IF EXISTS "Chamados" CASCADE;
DROP TABLE IF EXISTS "SLACategorias" CASCADE;
DROP TABLE IF EXISTS "Usuarios" CASCADE;
DROP TABLE IF EXISTS "GruposEmpresas" CASCADE;

-- 1. GruposEmpresas (Matriz e Filial)
CREATE TABLE "GruposEmpresas" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdExterno" VARCHAR(100) NOT NULL,
    "Nome" VARCHAR(150) NOT NULL,
    "Tipo" INT NOT NULL DEFAULT 0, -- 0=MATRIZ, 1=FILIAL
    "MatrizId" INT NULL,
    CONSTRAINT "FK_GruposEmpresas_GruposEmpresas_MatrizId" 
        FOREIGN KEY ("MatrizId") REFERENCES "GruposEmpresas" ("Id") ON DELETE RESTRICT
);

-- 2. Usuarios
CREATE TABLE "Usuarios" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdExterno" VARCHAR(100) NOT NULL,
    "Nome" VARCHAR(150) NOT NULL,
    "Email" VARCHAR(150) NOT NULL UNIQUE,
    "SenhaHash" VARCHAR(255) NOT NULL,
    "GrupoEmpresaId" INT NOT NULL,
    "Papel" INT NOT NULL DEFAULT 0, -- 0=CLIENTE, 1=AGENTE, 2=SUPERVISOR, 3=ADMIN
    CONSTRAINT "FK_Usuarios_GruposEmpresas_GrupoEmpresaId" 
        FOREIGN KEY ("GrupoEmpresaId") REFERENCES "GruposEmpresas" ("Id") ON DELETE RESTRICT
);

-- 3. SLACategorias
CREATE TABLE "SLACategorias" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Produto" VARCHAR(100) NOT NULL,
    "Categoria" VARCHAR(100) NOT NULL,
    "Prioridade" INT NOT NULL, -- 0=BAIXA, 1=MEDIA, 2=ALTA, 3=CRITICA
    "TempoResposta" INT NOT NULL, -- Em horas
    "TempoResolucao" INT NOT NULL -- Em horas
);

-- 4. Chamados
CREATE TABLE "Chamados" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CodigoPublico" VARCHAR(50) NOT NULL UNIQUE,
    "UsuarioId" INT NOT NULL,
    "GrupoEmpresaId" INT NOT NULL,
    "AgenteId" INT NULL,
    "SlaCategoriaId" INT NULL,
    "Produto" VARCHAR(100) NOT NULL,
    "Categoria" VARCHAR(100) NOT NULL,
    "Descricao" TEXT NOT NULL,
    "Status" INT NOT NULL DEFAULT 0,      -- 0=ABERTO, 1=EM_ANDAMENTO, 2=AGUARDANDO_CLIENTE, 3=RESOLVIDO, 4=FECHADO
    "Prioridade" INT NOT NULL DEFAULT 1,  -- 0=BAIXA, 1=MEDIA, 2=ALTA, 3=CRITICA
    "PrazoResposta" TIMESTAMP WITH TIME ZONE NULL,
    "PrazoResolucao" TIMESTAMP WITH TIME ZONE NULL,
    "AguardandoDesde" TIMESTAMP WITH TIME ZONE NULL,
    "CriadoEm" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ResolvidoEm" TIMESTAMP WITH TIME ZONE NULL,
    "FechadoEm" TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT "FK_Chamados_Usuarios_UsuarioId" 
        FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Chamados_Usuarios_AgenteId" 
        FOREIGN KEY ("AgenteId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Chamados_GruposEmpresas_GrupoEmpresaId" 
        FOREIGN KEY ("GrupoEmpresaId") REFERENCES "GruposEmpresas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Chamados_SLACategorias_SlaCategoriaId" 
        FOREIGN KEY ("SlaCategoriaId") REFERENCES "SLACategorias" ("Id") ON DELETE RESTRICT
);

-- 5. Interacoes
CREATE TABLE "Interacoes" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ChamadoId" INT NOT NULL,
    "AutorId" INT NOT NULL,
    "Tipo" INT NOT NULL DEFAULT 0, -- 0=PUBLICA, 1=NOTA_INTERNA
    "Mensagem" TEXT NOT NULL,
    "Anexos" TEXT NULL,
    "CriadoEm" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FK_Interacoes_Chamados_ChamadoId" 
        FOREIGN KEY ("ChamadoId") REFERENCES "Chamados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Interacoes_Usuarios_AutorId" 
        FOREIGN KEY ("AutorId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);

-- 6. LogsAuditoria
CREATE TABLE "LogsAuditoria" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ChamadoId" INT NOT NULL,
    "UsuarioId" INT NOT NULL,
    "Acao" VARCHAR(100) NOT NULL,
    "CampoAlterado" VARCHAR(100) NOT NULL,
    "ValorAnterior" TEXT NOT NULL,
    "ValorNovo" TEXT NOT NULL,
    "Data" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FK_LogsAuditoria_Chamados_ChamadoId" 
        FOREIGN KEY ("ChamadoId") REFERENCES "Chamados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LogsAuditoria_Usuarios_UsuarioId" 
        FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);