// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908230311_AdicionarAlertasSla")]
    partial class AdicionarAlertasSla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AlertaSla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReconhecidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReconhecidoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReconhecidoEm");

                    b.HasIndex("ReconhecidoPorId");

                    b.HasIndex("ChamadoId", "Tipo");

                    b.ToTable("AlertasSla");
                });

            modelBuilder.Entity("backend.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AguardandoDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AlertaEstouroSlaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AlertaRespostaAtrasadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AlertaRiscoSlaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoEmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrazoResolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PrazoResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SlaCategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("GrupoEmpresaId");

                    b.HasIndex("SlaCategoriaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Status", "PrazoResolucao");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("backend.Models.GrupoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MatrizId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatrizId");

                    b.ToTable("GruposEmpresas");
                });

            modelBuilder.Entity("backend.Models.Interacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anexos")
                        .HasColumnType("text");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ChamadoId");

                    b.ToTable("Interacoes");
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampoAlterado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorNovo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("backend.Models.SLACategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TempoResolucao")
                        .HasColumnType("integer");

                    b.Property<int>("TempoResposta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SLACategorias");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GrupoEmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEmpresaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend.Models.AlertaSla", b =>
                {
                    b.HasOne("backend.Models.Chamado", "Chamado")
                        .WithMany("AlertasSla")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "ReconhecidoPor")
                        .WithMany()
                        .HasForeignKey("ReconhecidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");

                    b.Navigation("ReconhecidoPor");
                });

            modelBuilder.Entity("backend.Models.Chamado", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Agente")
                        .WithMany("ChamadosAtendidos")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.GrupoEmpresa", "GrupoEmpresa")
                        .WithMany("Chamados")
                        .HasForeignKey("GrupoEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.SLACategoria", "SlaCategoria")
                        .WithMany("Chamados")
                        .HasForeignKey("SlaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("ChamadosCriados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("GrupoEmpresa");

                    b.Navigation("SlaCategoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.GrupoEmpresa", b =>
                {
                    b.HasOne("backend.Models.GrupoEmpresa", "Matriz")
                        .WithMany("Filiais")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("backend.Models.Interacao", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Autor")
                        .WithMany("Interacoes")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.HasOne("backend.Models.Chamado", "Chamado")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.GrupoEmpresa", "GrupoEmpresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEmpresa");
                });

            modelBuilder.Entity("backend.Models.Chamado", b =>
                {
                    b.Navigation("AlertasSla");

                    b.Navigation("Interacoes");

                    b.Navigation("LogsAuditoria");
                });

            modelBuilder.Entity("backend.Models.GrupoEmpresa", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Filiais");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.SLACategoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("ChamadosAtendidos");

                    b.Navigation("ChamadosCriados");

                    b.Navigation("Interacoes");

                    b.Navigation("LogsAuditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
